CREATE TABLE users (
    userId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(255) UNIQUE,
    passwordHash VARCHAR(255),
    telegram_id VARCHAR(255),
    username VARCHAR(255),
    picture VARCHAR(255),
    firstName VARCHAR(255),
    lastName VARCHAR(255),
    hobbies VARCHAR(255),
    interests VARCHAR(255)
);

CREATE TABLE groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    icon VARCHAR(255),
    owner_id BIGINT NOT NULL,
    CONSTRAINT fk_groups_owner FOREIGN KEY (owner_id) REFERENCES users(userId)
);

CREATE TABLE group_members (
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (group_id, user_id),
    CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_group_members_user FOREIGN KEY (user_id) REFERENCES users(userId) ON DELETE CASCADE
);

CREATE TABLE links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(64) UNIQUE NOT NULL,
    type VARCHAR(255) NOT NULL,
    entityId BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    createdAt TIMESTAMPTZ NOT NULL,
    expireAt TIMESTAMPTZ,
    active BOOLEAN NOT NULL,
    CONSTRAINT fk_links_owner FOREIGN KEY (owner_id) REFERENCES users(userId)
);

CREATE TABLE wishlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    color VARCHAR(255),
    icon VARCHAR(255),
    owner_id BIGINT NOT NULL,
    CONSTRAINT fk_wishlists_owner FOREIGN KEY (owner_id) REFERENCES users(userId)
);

CREATE TABLE wishes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    color VARCHAR(255),
    wishlist_id BIGINT NOT NULL,
    CONSTRAINT fk_wishes_wishlist FOREIGN KEY (wishlist_id) REFERENCES wishlists(id) ON DELETE CASCADE
);

CREATE INDEX idx_groups_owner_id ON groups(owner_id);
CREATE INDEX idx_group_members_user_id ON group_members(user_id);
CREATE INDEX idx_links_owner_id ON links(owner_id);
CREATE INDEX idx_wishlists_owner_id ON wishlists(owner_id);
CREATE INDEX idx_wishes_wishlist_id ON wishes(wishlist_id);