CREATE TABLE IF NOT EXISTS blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(200) NOT NULL UNIQUE,
    title VARCHAR(500) NOT NULL,
    preview_image VARCHAR(255),
    preview_content TEXT,
    content TEXT NOT NULL,
    published_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON blog_posts(slug);