spring:
    application:
        name: corp-wishlist

    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:wishlist}
        username: ${DB_USER:postgres}
        password: ${DB_PASSWORD:pass}

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        format-sql: true
