spring:
    application:
        name: corp-wishlist

    profiles:
        default: dev

jwt:
  secret: "MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=" #Тестовый ключ, TODO() заменить в дальнейшем на нормальный

telegram:
  bot_token: ${BOT_TOKEN}